/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Distributed_System_part1;

import Distributed_System_part1.Nodes.Broker;
import Distributed_System_part1.Nodes.UserNode;
import Distributed_System_part1.Util.Util;
import com.drew.imaging.ImageMetadataReader;
import com.drew.imaging.ImageProcessingException;
import com.drew.metadata.Metadata;
import com.drew.metadata.Directory;
import com.drew.metadata.MetadataException;
import com.drew.metadata.Tag;

import java.io.File;
import java.io.IOException;

import java.util.Locale;

public class EventDeliverySystem {

    public static void main(String[] args) {
        if (args[0].toLowerCase(Locale.ROOT).startsWith("use")) {
            UserNode userNode = new UserNode();
        } else if (args[0].toLowerCase(Locale.ROOT).startsWith("bro")) {
            Thread brokerThread = new Thread(new Broker());
            brokerThread.start();
        } else if (args[0].toLowerCase(Locale.ROOT).startsWith("test")) {
            File file = new File(
                    Thread.currentThread().getContextClassLoader().getResource("videos/birds.mp4").getPath());
            try {
                Metadata metadata = ImageMetadataReader.readMetadata(file);

                print(metadata, "Using ImageMetadataReader");
            } catch (ImageProcessingException e) {
                print(e);
            } catch (IOException e) {
                print(e);
            }
        }
    }

    private static void print(Metadata metadata, String method) {
        System.out.println();
        System.out.println("-------------------------------------------------");
        System.out.print(' ');
        System.out.print(method);
        System.out.println("-------------------------------------------------");
        System.out.println();

        //
        // A Metadata object contains multiple Directory objects
        //
        for (Directory directory : metadata.getDirectories()) {
            System.out.println("Directory:" + directory.toString());
            //
            // Each Directory stores values in Tag objects
            //

            for (Tag tag : directory.getTags()) {
                System.out.println(tag.getTagType() + " - " + tag);
            }
            try {
                System.out.println(directory.getInt(259));

            } catch (MetadataException e) {
                e.printStackTrace();
            }

            //
            // Each Directory may also contain error messages
            //
            for (String error : directory.getErrors()) {
                System.err.println("ERROR: " + error);
            }
        }
    }

    private static void print(Exception exception) {
        System.err.println("EXCEPTION: " + exception);
    }

}
