/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Distributed_System_part1;

class EventDeliverySystemTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
}
